databases:
  - name: avivandofuego-db
    plan: free
    databaseName: avivandofuego
    user: appuser

services:
  - type: web
    name: ministerio-avivando-el-fuego
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: avivandofuego-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: "10000"
    autoDeploy: true
    healthCheckPath: /api/hello
